src/Entity/Commande.php
<?php

namespace App\Entity;

use App\Repository\CommandeRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CommandeRepository::class)
 */
class Commande
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="decimal", precision=11, scale=2)
     */
    private $montant;

    /**
     * @ORM\Column(type="date")
     */
    private $date_enregistrement;

    /**
     * @ORM\Column(type="string", length=20)
     */
    private $etat;

    /**
     * @ORM\ManyToOne(targetEntity=Membre::class, inversedBy="commandes")
     * @ORM\JoinColumn(nullable=false)
     */
    private $membre;

    /**
     * @ORM\OneToMany(targetEntity=Detail::class, mappedBy="commande", orphanRemoval=true)
     */
    private $details;

    public function __construct()
    {
        $this->details = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getMontant(): ?string
    {
        return $this->montant;
    }

    public function setMontant(string $montant): self
    {
        $this->montant = $montant;

        return $this;
    }

    public function getDateEnregistrement(): ?\DateTimeInterface
    {
        return $this->date_enregistrement;
    }

    public function setDateEnregistrement(\DateTimeInterface $date_enregistrement): self
    {
        $this->date_enregistrement = $date_enregistrement;

        return $this;
    }

    public function getEtat(): ?string
    {
        return $this->etat;
    }

    public function setEtat(string $etat): self
    {
        $this->etat = $etat;

        return $this;
    }

    public function getMembre(): ?Membre
    {
        return $this->membre;
    }

    public function setMembre(?Membre $membre): self
    {
        $this->membre = $membre;

        return $this;
    }

    /**
     * @return Collection|Detail[]
     */
    public function getDetails(): Collection
    {
        return $this->details;
    }

    public function addDetail(Detail $detail): self
    {
        if (!$this->details->contains($detail)) {
            $this->details[] = $detail;
            $detail->setCommande($this);
        }

        return $this;
    }

    public function removeDetail(Detail $detail): self
    {
        if ($this->details->removeElement($detail)) {
            // set the owning side to null (unless already changed)
            if ($detail->getCommande() === $this) {
                $detail->setCommande(null);
            }
        }

        return $this;
    }
}

src/Entity/Membre.php
<?php

namespace App\Entity;

use App\Repository\MembreRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=MembreRepository::class)
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
class Membre implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $prenom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $adresse;

    /**
     * @ORM\Column(type="integer", columnDefinition="INT(5) UNSIGNED ZEROFILL")
     */
    private $cp;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $ville;

    /**
     * @ORM\Column(type="string", length=10, nullable=true)
     */
    private $tel;

    /**
     * @ORM\OneToMany(targetEntity=Commande::class, mappedBy="membre", orphanRemoval=true)
     */
    private $commandes;

    public function __construct()
    {
        $this->commandes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getCp(): ?string
    {
        return $this->cp;
    }

    public function setCp(string $cp): self
    {
        $this->cp = $cp;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(string $ville): self
    {
        $this->ville = $ville;

        return $this;
    }

    public function getTel(): ?string
    {
        return $this->tel;
    }

    public function setTel(?string $tel): self
    {
        $this->tel = $tel;

        return $this;
    }

    /**
     * @return Collection|Commande[]
     */
    public function getCommandes(): Collection
    {
        return $this->commandes;
    }

    public function addCommande(Commande $commande): self
    {
        if (!$this->commandes->contains($commande)) {
            $this->commandes[] = $commande;
            $commande->setMembre($this);
        }

        return $this;
    }

    public function removeCommande(Commande $commande): self
    {
        if ($this->commandes->removeElement($commande)) {
            // set the owning side to null (unless already changed)
            if ($commande->getMembre() === $this) {
                $commande->setMembre(null);
            }
        }

        return $this;
    }
}

src/Form/MembreType.php
<?php

namespace App\Form;

use App\Entity\Membre;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class MembreType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('email')
            ->add('roles', ChoiceType::class,[
               "choices"=>[
                   "Administrateur"=> "ROLE_ADMIN",
                   "Membre"=>"ROLE_USER",
                   "Vendeur"=>"ROLE_SELLER"
               ],
               "multiple"=>true,
               "expanded"=>true 
            ])
            ->add('password', TextType::class,[
                "mapped"=>false,
                "required"=>false
            ])
            ->add('nom')
            ->add('prenom')
            ->add('adresse')
            ->add('cp')
            ->add('ville')
            ->add('tel')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Membre::class,
        ]);
    }
}

src/Controller/MembreController.php
<?php

namespace App\Controller;

use App\Entity\Membre;
use App\Form\MembreType;
use App\Repository\MembreRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/admin/membre")
 */
class MembreController extends AbstractController
{
    /**
     * @Route("/", name="membre_index", methods={"GET"})
     */
    public function index(MembreRepository $membreRepository): Response
    {
        return $this->render('membre/index.html.twig', [
            'membres' => $membreRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="membre_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $membre = new Membre();
        $form = $this->createForm(MembreType::class, $membre);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($membre);
            $entityManager->flush();

            return $this->redirectToRoute('membre_index');
        }

        return $this->render('membre/new.html.twig', [
            'membre' => $membre,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="membre_show", methods={"GET"})
     */
    public function show(Membre $membre): Response
    {
        return $this->render('membre/show.html.twig', [
            'membre' => $membre,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="membre_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Membre $membre): Response
    {
        $form = $this->createForm(MembreType::class, $membre);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('membre_index');
        }

        return $this->render('membre/edit.html.twig', [
            'membre' => $membre,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="membre_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Membre $membre): Response
    {
        if ($this->isCsrfTokenValid('delete'.$membre->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($membre);
            $entityManager->flush();
        }

        return $this->redirectToRoute('membre_index');
    }
}

templates/membre/_delete_form.html.twig
<form method="post" action="{{ path('membre_delete', {'id': membre.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ membre.id) }}">
    <button class="btn">Delete</button>
</form>

templates/membre/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/membre/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Membre{% endblock %}

{% block body %}
    <h1>Edit Membre</h1>

    {{ include('membre/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('membre_index') }}">back to list</a>

    {{ include('membre/_delete_form.html.twig') }}
{% endblock %}

templates/membre/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Membre index{% endblock %}

{% block body %}
    <h1>Membre index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Email</th>
                <th>Roles</th>
                <th>Nom</th>
                <th>Prenom</th>
                <th>Adresse</th>
                <th>Cp</th>
                <th>Ville</th>
                <th>Tel</th>
                <th>Nbr Commandes</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for membre in membres %}
            <tr>
                <td>{{ membre.id }}</td>
                <td>{{ membre.email }}</td>
                <td>{{ membre.roles ? membre.roles|json_encode : '' }}</td>
                <td>{{ membre.nom }}</td>
                <td>{{ membre.prenom }}</td>
                <td>{{ membre.adresse }}</td>
                <td>{{ membre.cp }}</td>
                <td>{{ membre.ville }}</td>
                <td>{{ membre.tel }}</td>
                <td>{{ membre.commandes|length }}</td>
                <td>
                    <a href="{{ path('membre_show', {'id': membre.id}) }}">show</a>
                    <a href="{{ path('membre_edit', {'id': membre.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="11">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('membre_new') }}">Create new</a>
{% endblock %}

templates/membre/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Membre{% endblock %}

{% block body %}
    <h1>Create new Membre</h1>

    {{ include('membre/_form.html.twig') }}

    <a href="{{ path('membre_index') }}">back to list</a>
{% endblock %}

templates/membre/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Membre
{% endblock %}

{% block body %}
	<h1>Membre</h1>

	<table class="table">
		<tbody>
			<tr>
				<th>Id</th>
				<td>{{ membre.id }}</td>
			</tr>
			<tr>
				<th>Email</th>
				<td>{{ membre.email }}</td>
			</tr>
			<tr>
				<th>Roles</th>
				<td>{{ membre.roles ? membre.roles|json_encode : '' }}</td>
			</tr>
			<tr>
				<th>Password</th>
				{# <td>{{ membre.password }}</td> #}
				<td>*****</td>
			</tr>
			<tr>
				<th>Nom</th>
				<td>{{ membre.nom }}</td>
			</tr>
			<tr>
				<th>Prenom</th>
				<td>{{ membre.prenom }}</td>
			</tr>
			<tr>
				<th>Adresse</th>
				<td>{{ membre.adresse }}</td>
			</tr>
			<tr>
				<th>Cp</th>
				<td>{{ membre.cp }}</td>
			</tr>
			<tr>
				<th>Ville</th>
				<td>{{ membre.ville }}</td>
			</tr>
			<tr>
				<th>Tel</th>
				<td>{{ membre.tel }}</td>
			</tr>
		</tbody>
	</table>


	<a href="{{ path('membre_index') }}">back to list</a>

	<a href="{{ path('membre_edit', {'id': membre.id}) }}">edit</a>

	{{ include('membre/_delete_form.html.twig') }}

	<h2>
		liste de ses commandes</h2>
<table class="table">
        <thead class="thead-dark">
            <tr>
                <th>Id</th>
				<th>Date</th>
                <th>Montant</th>
                <th>Etat</th>
            </tr>
        </thead>
 <tbody>

		{% for commande in membre.commandes %}
			<tr>
				<td>{{ commande.id }}</td>
				<td>{{ commande.dateEnregistrement|date("d/m/Y") }}</td>
                <td>{{ commande.montant }} €</td>
                <td>{{ commande.etat }}</td>
                <td>{{ commande.membre.nom }}</td>
                <td>{{ commande.membre.prenom }}</td>
			</tr>
			{% else %}
			<td colspan=4>Aucune commande encours pour ce membre</td> 
		{% endfor %}
		<br><br>
</tbody>


{% endblock %}